name: Trigger auto deployment for container-app-qgnjjgaacht5e

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-qgnjjgaacht5e-AutoDeployTrigger-ac23d4c4-5cf7-4114-9e63-18bfd57987aa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQGNJJGAACHT5E_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQGNJJGAACHT5E_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQGNJJGAACHT5E_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPQGNJJGAACHT5E_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQGNJJGAACHT5E_REGISTRY_PASSWORD }}
          containerAppName: container-app-qgnjjgaacht5e
          resourceGroup: appspacesragappbca5a704
          imageToBuild: default/container-app-qgnjjgaacht5e:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


